Repository FA24SE112-Tech-Gadgets/TechGadgetsMobile, pull requests merged in 2024-10, with the labels that each got.

#15 fix CI/CD
  .github/workflows/deploy-ch-play.yml
Labels: bug

#16 fix deployment
  .github/workflows/deploy-ch-play.yml
  android/app/build.gradle
Labels: bug

#17 fix ci/cd deployment
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/kietpt2003/WhatEat/MainActivity.kt
  android/app/src/main/java/com/kietpt2003/WhatEat/MainApplication.kt
  android/app/src/main/res/values/strings.xml
  android/settings.gradle
  app.json
  eas.json
Labels: migrations

#18 fix
  android/app/build.gradle
  android/app/my-upload-key.keystore
  android/gradle.properties
  app.json
  eas.json
Labels: migrations

#19 fix deploy
  .github/workflows/deploy-ch-play.yml
  android/app/build.gradle
  android/gradle.properties
Labels: bug

#20 Update Tech Gadget to v1.0.3
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  android/settings.gradle
  app.json
Labels: update prod, migrations

#21 Change profile password
  .vscode/settings.json
  App.js
  android/app/build.gradle
  app.json
  components/Authorization/LoginScreen.js
  components/Authorization/RegisterScreen.js
  components/Authorization/VerifyCodeScreen.js
  components/Buyer/BuyerHome.js
  components/Buyer/BuyerPersonal.js
  components/Buyer/BuyerProfile.js
  components/Buyer/Detail/Detail.js
  components/Buyer/Detail/ProductDetail.js
  components/Buyer/FavouriteGagdets.js
  components/CustomComponents/ChangeProfile.js
  components/CustomComponents/PasswordAndSecure.js
  components/Seller/BusinessRegistrationCertificate.js
  components/Seller/CertificateDetail.js
  components/Seller/CertificateHistory.js
  navigators/RootNavigator.js
  navigators/SellerNavigator.js
  package-lock.json
  package.json
Labels: enhancement

#22 Migrate to prod
  .vscode/settings.json
  App.js
  android/app/build.gradle
  app.json
  components/Authorization/LoginScreen.js
  components/Authorization/RegisterScreen.js
  components/Authorization/VerifyCodeScreen.js
  components/Buyer/BuyerHome.js
  components/Buyer/BuyerPersonal.js
  components/Buyer/BuyerProfile.js
  components/Buyer/Detail/Detail.js
  components/Buyer/Detail/ProductDetail.js
  components/Buyer/FavouriteGagdets.js
  components/CustomComponents/ChangeProfile.js
  components/CustomComponents/PasswordAndSecure.js
  components/Seller/BusinessRegistrationCertificate.js
  components/Seller/CertificateDetail.js
  components/Seller/CertificateHistory.js
  navigators/RootNavigator.js
  navigators/SellerNavigator.js
  package-lock.json
  package.json
Labels: update prod

#23 HomePage
  android/app/build.gradle
  app.json
  components/Buyer/BuyerHome.js
Labels: enhancement

#24 Migrate to prod
  android/app/build.gradle
  app.json
  components/Buyer/BuyerHome.js
Labels: update prod

#25 Detail Gadget
  components/Authorization/LoginScreen.js
  components/Buyer/BuyerHome.js
  components/Buyer/Detail/GadgetDetail.js
  navigators/RootNavigator.js
Labels: enhancement
