Repository FA24SE112-Tech-Gadgets/TechGadgetsMobile, pull requests merged in 2024-09, with the labels that each got.

#1 test
  navigators/test.js
Labels: update main

#2 update tech gadgets to v1.0.2
  app.json
  locales/en.json
  locales/vi.json
  package.json
Labels: update main

#3 Prod
  .github/workflows/deploy-ch-play.yml
  android/app/build.gradle
Labels: update main

#4 fix
  .github/workflows/deploy-ch-play.yml
  app.json
Labels: update main

#5 fix
  .github/workflows/deploy-ch-play.yml
Labels: update main

#6 delete test file
  navigators/test.js
Labels: enhancement

#7 Update prod
  navigators/test.js
Labels: update prod

#8 Update MapKeys
  app.json
  components/Authorization/RegisterScreen.js
  components/CustomComponents/ChangeProfile.js
  components/CustomComponents/ChooseLocation.js
  components/CustomComponents/CustomMapModal.js
  components/CustomComponents/RegisterAddress.js
  components/Customer/CustomerDishDetail.js
  components/Restaurant/RestaurantDishDetail.js
  package-lock.json
Labels: enhancement

#9 Full authorize
  .env
  App.js
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-hdpi/notification_icon.png
  android/app/src/main/res/drawable-mdpi/notification_icon.png
  android/app/src/main/res/drawable-xhdpi/notification_icon.png
  android/app/src/main/res/drawable-xxhdpi/notification_icon.png
  android/app/src/main/res/drawable-xxxhdpi/notification_icon.png
  android/app/src/main/res/values/colors.xml
  android/gradle.properties
  app.json
  components/Authorization/AuthContext.js
  components/Authorization/AuthRoute.js
  components/Authorization/LoginScreen.js
  components/Authorization/RegisterScreen.js
  components/Authorization/VerifyCodeScreen.js
  components/Authorization/api.js
  components/Customer/CustomerHome.js
  components/Customer/CustomerProfile.js
  components/Notification/BackgroundTask.js
  components/Restaurant/RestaurantProfile.js
  components/UploadFile/UploadFileDemo.js
  navigators/CustomerNavigator.js
  navigators/RestaurantNavigator.js
  navigators/RootNavigator.js
  package-lock.json
  package.json
Labels: enhancement

#10 Update prod
  .env
  App.js
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-hdpi/notification_icon.png
  android/app/src/main/res/drawable-mdpi/notification_icon.png
  android/app/src/main/res/drawable-xhdpi/notification_icon.png
  android/app/src/main/res/drawable-xxhdpi/notification_icon.png
  android/app/src/main/res/drawable-xxxhdpi/notification_icon.png
  android/app/src/main/res/values/colors.xml
  android/gradle.properties
  app.json
  components/Authorization/AuthContext.js
  components/Authorization/AuthRoute.js
  components/Authorization/LoginScreen.js
  components/Authorization/RegisterScreen.js
  components/Authorization/VerifyCodeScreen.js
  components/Authorization/api.js
  components/CustomComponents/ChangeProfile.js
  components/CustomComponents/ChooseLocation.js
  components/CustomComponents/CustomMapModal.js
  components/CustomComponents/RegisterAddress.js
  components/Customer/CustomerDishDetail.js
  components/Customer/CustomerHome.js
  components/Customer/CustomerProfile.js
  components/Notification/BackgroundTask.js
  components/Restaurant/RestaurantDishDetail.js
  components/Restaurant/RestaurantProfile.js
  components/UploadFile/UploadFileDemo.js
  navigators/CustomerNavigator.js
  navigators/RestaurantNavigator.js
  navigators/RootNavigator.js
  package-lock.json
  package.json
Labels: update prod

#11 Update TechGadget to v1.0.3
  android/app/build.gradle
  app.json
  locales/en.json
  locales/vi.json
  package.json
Labels: enhancement

#12 Update prod
  android/app/build.gradle
  app.json
  locales/en.json
  locales/vi.json
  package.json
Labels: update prod
